name: Feature Request
description: Suggest a feature to improve OpenComic
title: "[Feature Request]: "
labels: "enhancement"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.
        required: true
- type: textarea
  attributes:
    label: Describe your suggested feature
    description: Please add a clear and concise description of the feature you want in OpenComic..
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the feature here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Sample file
    description: If it is related to the feature request.
  validations:
    required: false